### ISSUE TITLE
dpms doesn't work with background colour.

### ISSUE THREAD

**Issue by anton-tsyganenko** [i3/i3lock#32]
If I run `i3lock -d`, the screen turns off, but if I run `i3lock -d -c 000000`, the screen turns off and then turns on back after about a second.

Arch linux, Xorg 1.17.2, i3lock 2.7.

**Comment by stapelberg** [comment]
I don’t see how the color would change anything. It doesn’t take a different code path, aside from parsing the option of course.

Regardless, I think it’s time to rip out the DPMS feature entirely. It never worked well, and users are better off using a wrapper script with xset’s DPMS settings.

**Comment by rodfersou** [comment]
well.. here it worked really well and that's a shame it is not available anymore.

I didn't like this change.  Also, the wrapper documented in the man page didn't work, my monitor didn't turn off on lock anymore.

**Comment by stapelberg** [comment]
With the wrapper described in the manpage, the monitor turns off after a specific timeout, not directly on lock.

**Comment by rodfersou** [comment]
this command didn't work on ubuntu ``trap revert SIGHUP SIGINT SIGTERM``

**Comment by rodfersou** [comment]
also, how can I make the monitor turn off directly on lock?

**Comment by rodfersou** [comment]
well.. I'll try to compile a version before this change here while I din't find another alternative

**Comment by stapelberg** [comment]
> this command didn't work on ubuntu trap revert SIGHUP SIGINT SIGTERM

Which shell are you using? In which version? Try removing the SIG prefixes, i.e. `trap revert HUP INT TERM`.

> also, how can I make the monitor turn off directly on lock?

You could run something like `sleep 1 && xset dpms force off`, or just reduce the DPMS timeout.

**Comment by rodfersou** [comment]
thank you

I'm using ZSH, but I think i3 uses bash to run the shortcut

**Comment by rodfersou** [comment]
Removing the SIG prefixes the error is fixed

**Comment by wheelcomplex** [comment]
For the one who still missing the DPMS ability a PR is ready for test: https://github.com/i3/i3lock/pull/267
